export let p = {
    player: "",
    countX: "",
    countY: "",
    remainX: "",
    remainY: "",
    mw: "",
    mh: "",
    map: "",
    screenWidth: "",
    screenHeight: "",
    tcx: 0,
    tcy: 0,
    ctx: "",
    canvasP: "",
    ctxP:"",
    mapEndX: "",
    mapEndY: "",
    start : false,
}